services:
  db:
    image: postgres:14.11
    env_file:
      - .env
    container_name: db_container
    command: -p 5433
    expose:
      - 5433
    ports:
      - 5433:5433
    volumes:
      - database:/var/lib.postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: app
    depends_on:
      - db
    command: [ "/multiparsing/app.sh" ]
    volumes:
      - .:/app

  avito:
    build:
      context: .
    env_file:
      - .env
    container_name: avito_parser
    depends_on:
      - db
      - app
    command: [ "/multiparsing/avito.sh" ]
    volumes:
      - .:/avito

volumes:
  database: